modLoader = "javafml"
loaderVersion = "${neoforge_loader_range}"
license = "CC BY-NC-ND 4.0"
showAsResourcePack = false

[[mods]]
    modId = "whatdidijustkill"
    version = "${version}"
    displayName = "What Did I Just Kill?"
    displayURL = "https://github.com/tristankechlo/WhatDidIJustKill"
    logoFile = "pack.png"
    authors = "Buecher_wurm"
    description = '''displays a small toast with information about the mob you just killed'''

[[mixins]]
    config = "whatdidijustkill.mixins.json"

[[dependencies.whatdidijustkill]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neoforge_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.whatdidijustkill]]
    modId = "minecraft"
    type = "required"
    versionRange = "${version_range}"
    ordering = "NONE"
side = "BOTH"
