plugins {
    id 'idea'
    id 'net.neoforged.gradle.userdev' version '7.0.180'
    id 'java-library'
}

base {
    version = "${minecraft_version}-${mod_version}"
    archivesBaseName = "${mod_id}-neoforge"
}

runs {
    client {
        modSource project.sourceSets.main
        workingDirectory file('runs')
    }
    server {
        modSource project.sourceSets.main
        workingDirectory file('runs')
        programArgument '--nogui'
    }
}

dependencies {
    implementation "net.neoforged:neoforge:${neoforge_version}"
    compileOnly project(":common")

    compileOnly group: 'com.google.auto.service', name: 'auto-service', version: auto_service_version
    annotationProcessor group: 'com.google.auto.service', name: 'auto-service', version: auto_service_version
}

// NeoGradle compiles the game, but we don't want to add our common code to the game's code
Spec<Task> notNeoTask = { Task it -> !it.name.startsWith("neo") } as Spec<Task>

tasks.withType(JavaCompile).matching(notNeoTask).configureEach {
    source(project(":common").sourceSets.main.allSource)
}

processResources {
    from project(":common").sourceSets.main.resources
    exclude("whatdidijustkill.accesswidener")
}
